using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace QuestionnaireLib
{
    [Serializable]
    public enum AnomalyDetailLevel
    {
        DEFAULT,
        LOW,
        HIGH
    }

    public interface SubmissionAnomaly
    {
        string Description { get; }
        DateTime Date { get; }
        AnomalyDetailLevel DetailLevel { get; }
    }

    [Serializable]
    public class DifferentHostAnomaly : SubmissionAnomaly
    {
        private readonly string _description = "Access from different hosts";
        private DateTime _date;
        private string _assignedHostAddress;
        private string _differentHostAddress;
        private readonly AnomalyDetailLevel _detailLevel = AnomalyDetailLevel.DEFAULT;

        public string Description { get { return _description; }}
        public DateTime Date { get { return _date; } }
        public string AssignedHostAddress { get { return _assignedHostAddress; } }
        public string DifferentHostAddress { get { return _differentHostAddress; } }
        public AnomalyDetailLevel DetailLevel { get { return _detailLevel; } }

        public DifferentHostAnomaly(string assignedHostAddress, string differentHostAddress)
        {
            
            _date = DateTime.Today;
            _assignedHostAddress = assignedHostAddress;
            _differentHostAddress = differentHostAddress;
            
            
        }
    }

    [Serializable]
    public class TamperedDataAnomaly : SubmissionAnomaly
    {
        private readonly string _description = "Submitted data does not match to generated data (i.e. data has been tampered)";
        private DateTime _date;
        private List<Question> _generatedList;
        private List<Question> _tamperedList;
        private AnomalyDetailLevel _detailLevel;

        public string Description { get { return _description; } }
        public DateTime Date { get { return _date; } }
        public List<Question> GeneratedList { get { return _generatedList; } }
        public List<Question> TamperedList { get { return _tamperedList; } }
        public AnomalyDetailLevel DetailLevel { get { return _detailLevel; } }

        /// <summary>
        /// Constructor for high level anomaly details.
        /// </summary>
        /// <param name="generatedList">The questions list generated by the server.</param>
        /// <param name="tamperedList">The submitted and tampered questions list.</param>
        public TamperedDataAnomaly(List<Question> generatedList, List<Question> tamperedList)
        {
            _date = DateTime.Today;
            _generatedList = generatedList;
            _tamperedList = tamperedList;
            _detailLevel = AnomalyDetailLevel.HIGH;
        }

        /// <summary>
        /// Constructor for low level anomaly detail.
        /// </summary>
        public TamperedDataAnomaly()
        {
            _date = DateTime.Today;
            _detailLevel = AnomalyDetailLevel.LOW;
        }
    }
}